wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715589914.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 23
      4: 3.8.19
      5: 0.16.5
      6: 4.39.1
      8:
      - 5
      13: linux-x86_64
ENV_HPT_mode:
  desc: null
  value: false
basic_nature:
  desc: null
  value: 29
online_simulation_factor:
  desc: null
  value: 4
seed:
  desc: null
  value: 2
